language: go
sudo: required
go:
  - 1.11.x
  
env:
  GO111MODULE=on
  CGO_ENABLED=0
  VERSION=v9.2
  RELEASE=rshell

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
          
addons:
  apt:
    update: true

script:
  bash build.sh

after_success:
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    dist/${RELEASE}-*
  skip_cleanup: true
  on:
    tags: true
