hostgroups:
- groupname: hostgroup01                  #Hostgroup name
  authmethod: alpha-env-ttt-key-su        #Hostgrout auth method name which in auth.yaml
  sshport: 22                             #SSH port, default: 22
  hosts:
  - 192.168.31.37                         #Ipv4 format

- groupname: hostgroup02
  authmethod: alpha-env-root-key
  sshport: 22
  hosts:
  - 192.168.31.63

- groupname: hostgroup-all
  authmethod: alpha-env-root-pass
  sshport: 22
  groups:
  - hostgroup01
  - hostgroup02
  hosts:
  - 192.168.31.197

- groupname: hostgroup03
  authmethod: alpha-env-root-pass
  sshport: 22
  groups:
  - hostgroup01
  - hostgroup02
  hosts:
  - 192.168.31.197
  hostranges:
  - from: 192.168.1.126
    to: 192.168.1.127