hostgroups:
- groupname: dev-centos_user_key
  authmethod: default_user_key
  hosts:
  - 192.168.31.63
  - 192.168.31.37

- groupname: dev-centos_user_key_root
  authmethod: default_user_key_root
  hosts:
  - 192.168.31.63
  - 192.168.31.37

- groupname: dev-centos_user_pass
  authmethod: default_user_pass
  hosts:
  - 192.168.31.63
  - 192.168.31.37

- groupname: dev-centos_user_pass_root
  authmethod: default_user_pass_root
  hosts:
  - 192.168.31.63
  - 192.168.31.37

- groupname: dev-centos_root_key
  authmethod: default_root_key
  hosts:
  - 192.168.31.63
  - 192.168.31.37

- groupname: dev-centos_root_pass
  authmethod: default_root_pass
  hosts:
  - 192.168.31.63
  - 192.168.31.37

- groupname: dev-suse_root_pass
  authmethod: default_root_pass
  hosts:
  - 192.168.1.126

- groupname: dev-centos-suse_root_pass
  authmethod: default_root_pass
  groups:
  - dev-centos_root_pass
  - dev-suse_root_pass
  hosts:
  - 192.168.31.197
